### PR TITLE
Fix light switch dupe bug.

### PR DESCRIPTION
**Pull request by Phylogeny**
It's based on the way Forge does it in BlockFlowerPot. I also fixed the light switch's first person rotation.

### CODE REVIEW

**Comment by Phylogeny** [comment]
Would you like the light switch to drop when the surface it's on is invalid? If so, I can push that change now; otherwise I can push the addition of backplates to it's block version models.

**Comment by Phylogeny** [comment]
Yes, I'm well awear of that:
1. It's hard to overstate just how little a single quad per block takes to render (even if it wasn't cashed; which it is).
2. 'Never visible unless...' means 'not never visible'; hence the importance of rendering the back.
3. This is why I mentioned the alternitive of causing them to break if their backing is broken.

**Comment by Phylogeny** [comment]
@MrCrayfish I've just gone ahead and pushed the addition of the backplates, as they cull when not needed anyway. Just let me know whether or not you want the light switches to break when the blocks they're on do.

**Comment by MrCrayfish** [comment]
Thanks for the duplication fix. I will most likely implement it so it drops like a button if the block it's on is destroyed.

**Comment by Phylogeny** [comment]
Sounds good. Also, I have a few PR questions: #243

**Pull request merged**
