### PR TITLE
Added recipes for new kitchen counters and kitchen counter sinks

### PR DESCRIPTION
**Pull request by HauntedCorpse**

### CODE REVIEW

**Comment by Ocelot5836** [comment]
I already added the recipes for all the kitchen counters and the counter sinks.

**Comment by mcBegins2Snow** [comment]
@HauntedCorpse Why do Colored Kitchen Counter Sinks have two "C"?
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/resources/assets/cfm/recipes/counter_sink_white.json#L13-L20

**Comment by MrCrayfish** [comment]
Fixed it @mcBegins2Snow

**Comment by HauntedCorpse** [comment]
Thought I double checked everything but obviously I didn't D:

**Pull request merged**
