### PR TITLE
Refactored configs to Forge's annotation-based system.

### PR DESCRIPTION
**Pull request by Phylogeny**
It's actually a very simple PR. Just _very_ large... and was even more tedious to do.

But the configs are much more organized now; and of course adding new ones is easier than ever (and fully localized) with the annotation system.

### CODE REVIEW

**Comment by MrCrayfish** [comment]
This will need updating

**Comment by Phylogeny** [comment]
I had changed the "cfm.x" format of the lang entries I added to the "x.cfm" format, since it seemed most typical of the lang file at the time, but not any more. Which format do you prefer?

**Comment by MrCrayfish** [comment]
I think the "cfm.x" is a better format for custom keys. Stuff like the advancements has to stay the same obviously.

**Comment by Phylogeny** [comment]
Ok. I'll push the change when I get back to my computer (~8 hrs).

**Comment by MrCrayfish** [comment]
Do you have Discord or anything so I chat privately?

**Comment by Phylogeny** [comment]
Yeah sure, I just joined your Discord server. I won't be back at my computer for ~9 hrs, though.

**Comment by Phylogeny** [comment]
I forgot that Discord has an phone app. I just installed it.

**Comment by MrCrayfish** [comment]
Okay, there is a slight issue. This change won't preserve the old config. I may have to hold off name changes until the 1.13 update as I know tons of people will be on my back about updating the config file. The best fix for now is the keep the same config format and property names. Once Forge 1.13 we can look at changing the names and format like in this PR.

**Comment by Phylogeny** [comment]
Ok. I might decide to modify this PR to preserve the structure of the preexisting config file (and the the file itself), for 1.12, but no promises. Either way, I agree that 1.13 will be a good opportunity to introduce better structure.

**Pull request closed without merging**
