### PR TITLE
[1.10 / 1.11 / 1.12] Add translation zhtw

### PR DESCRIPTION
**Pull request by hugoalh**
Please add translation zhtw into the mod. :)
Hope you can port to all of the versions.

### CODE REVIEW

**Comment by mcBegins2Snow** [comment]
The mod version has been updated to 5.3.0,author added some new items and rewrote language files.
So would you like to rewrite zh_tw according to newest lang file?
Simplified Chinese
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/resources/assets/cfm/lang/zh_cn.lang
English
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/blob/master/src/main/resources/assets/cfm/lang/en_us.lang

**Comment by hugoalh** [comment]
This pull request still can be use on 1.10 and 1.11, edited title for identify.
For 1.12, update will be progress if author confirm most of the changing is finish.

**Comment by mcBegins2Snow** [comment]
@MrCrayfish The host said he wants to create zh_tw to mc 1.10&1.11,but he doesn't know when 1.12's changing is finished so that he can't update.Would you like to talk your opinion?

**Comment by hugoalh** [comment]
**Update States:**
* Updated zh_tw.lang to compatible 1.10/1.11/1.12
* If need to separate the language file between 1.10/1.11 and 1.12, you can delete achievement/advancement section to reduce file size

**Comment by mcBegins2Snow** [comment]
For 1.12,the next version will update gui's i18n, #255 
My zh_cn is waiting for merging. #257

**Comment by hugoalh** [comment]
Updated to 1.12.2-5.4.1, compat to 1.10/1.11/1.12

**Pull request merged**
