### PR TITLE
Fix various TE crashes during rendering.

### PR DESCRIPTION
**Pull request by bloodmc**
There is some odd vanilla or Forge bug that causes the TESR to randomly receive AIR when getting the blockstate.

* Update TE renderers with generics which has been supported since 1.8.8.
* Clean up some code.

This PR fixes issue #45

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Thanks. I've been meaning to change this for a while now.

**Comment by Mariojacob7red** [comment]
Minecraft crashes when i put the mirror down and I had to go into the
.minecraft/config folder and change the settings a little. I forgot what
changed but I know it had to do with the mirror rendering i believe.

**Comment by ShadowCoder69** [comment]
@Mariojacob7red if you copy your (fixed) config file to an somewhere else cfm will generate a new one (without the fix) so you can check with a diff tool what changed

**Comment by Mariojacob7red** [comment]
Spwaking of the mirror, was it supposed to have reflection like a real mirror?

**Comment by Mariojacob7red** [comment]
*Speaking

**Comment by Mariojacob7red** [comment]
Also, the tv in the furniture mod for 1.8 crashes Minecraft after the conversation of the 2 guys talking to each other. P.S. ill use that tool today once i get home from school.

**Comment by Mariojacob7red** [comment]
I wasnt able to fix the tv.

**Pull request merged**
