### PR TITLE
Update zh_cn.lang

### PR DESCRIPTION
**Pull request by HaeDon**
Latest version of the translation

### CODE REVIEW

**Comment by mcBegins2Snow** [comment]
@HaeDon I can't find any change.

**Comment by HaeDon** [comment]
The number of rows is three more than the previous version, you didn't find it.
行数比上一个版本多了三行，你没发现

**Comment by MrCrayfish** [comment]
Is this ready to be merged?

**Comment by mcBegins2Snow** [comment]
@MrCrayfish I'm ready to merge.The author needn't merge his pr.

**Comment by HaeDon** [comment]
@MrCrayfish  Please compare the decision, don't believe any sentence

**Comment by MrCrayfish** [comment]
@HaeDon The problem is that I don't understand Chinese so it will be up to you guys to sort it out which is better translations.

**Pull request closed without merging**
