### PR TITLE
CraftTweaker Support

### PR DESCRIPTION
**Pull request by BlueAgent**
Hi MrCrayfish,

This pull requests adds CraftTweaker support.

Here is an [example script](https://gist.github.com/BlueAgent/a104380351014e23e9871dd7accde007) to test the functionality ([screenshot](https://i.imgur.com/sEAN0sA.png))

This pull request was created to see if it is okay to continue this and for any changes required and/or suggestions made.

Regards,
BlueAgent

P.S. Love your mod.

<details>
<summary>
This is kinda off-topic but... Click for details.
</summary>

If you use "minecraft:night_vision" like spawned in potions it won't match.
It turned out this was because the potion tag is missing "minecraft:" at the start ([screenshot](https://i.imgur.com/5hQJcVm.png)):

```
ItemStack stack = new ItemStack(Items.POTIONITEM, 2);
NBTTagCompound data = new NBTTagCompound();
data.setString("Potion", "night_vision");
stack.setTagCompound(data);
```

If you create the potion like this it will set the tag correctly:

```
ItemStack stack = new ItemStack(Items.POTIONITEM, 2);
PotionUtils.addPotionToItemStack(stack, PotionTypes.NIGHT_VISION);
```
</details>

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Yeah this would be awesome! You can definitely continue with the integration and I will merge it.

**Comment by BlueAgent** [comment]
I've finished the CraftTweaker support.
[Sample Script](https://gist.github.com/BlueAgent/a104380351014e23e9871dd7accde007)
[Sample CraftTweaker Log](https://gist.github.com/BlueAgent/f41f8fc2a9ca87beea8defb6ea6bb148)
[Album](https://imgur.com/a/uwRcZ6X)

**Comment by BlueAgent** [comment]
@MrCrayfish Did some manual testing.
Microwave doesn't support more than single item for the output so <minecraft:stick>.withAmount(4) only outputs 1 stick.
Runs without CraftTweaker installed as well as with CraftTweaker.
Runs in Singleplayer and on a Dedicated Server. (Interestingly the recipe shows up without 4 for the amount when playing multiplayer).

Changes will require a `gradlew setupDecompWorkspace` because of the new CraftTweaker dependency.

**Comment by BlueAgent** [comment]
Rebased in the latest from master, noticed that code indentation changed from tabs to spaces and have updated the pull request accordingly.

**Comment by BlueAgent** [comment]
Updated stale pull request (changes in build.gradle and Reference.java).
Also squashed the changes into a single commit.
@MrCrayfish This pull request is ready to be merged. Let me know if any changes are needed.

**Comment by MrCrayfish** [comment]
This will be merged in preparation of version 5.4.0, which will come out next week alongside the new modern sliding door.

**Comment by MrCrayfish** [comment]
If you can update it to use withAmount() for the currency, that would be awesome. I think consistency is key.

**Comment by BlueAgent** [comment]
MineBay was kinda different from the other machines for the RecipeData.
What you're buying made use of `RecipeData.setInput(stack)` and what you pay made use of `RecipeData.setCurrency(stack)` and `RecipeData.setPrice(int)`.
So the idea was to have it similar to that.

I've pushed a commit with the changes.
Here's how the script for MineBay works now:
```
// MineBay
mods.cfm.MineBay.addTrade(<minecraft:stick>.withAmount(42),<minecraft:diamond>.withAmount(13));
mods.cfm.MineBay.addTrade(<minecraft:apple>.withAmount(16),<minecraft:emerald>.withAmount(3));
mods.cfm.MineBay.addTrade(<minecraft:carrot>,<minecraft:emerald>);
mods.cfm.MineBay.remove(<minecraft:potion>.withTag({Potion: "night_vision"}));
```

Also is `addTrade` okay for mine bay, or should it be `addRecipe` since the other machines use that as well?

**Comment by BlueAgent** [comment]
@MrCrayfish please review the changes. Should be good to go.

**Comment by BlueAgent** [comment]
@MrCrayfish Is there any more changes that need to be made?

**Comment by MrCrayfish** [comment]
Sorry for the delay. I am happy with the naming you have gone for with the methods. Just going to check it out right now.

**Comment by MrCrayfish** [comment]
Just tested it, works perfectly! Merging now...

**Pull request merged**
