### PR TITLE
Removed \u00A7 chars causing startup crash on unix based systems

### PR DESCRIPTION
**Pull request by p455w0rd**
Also removed the refence to the banner..i figure it can be added back when the image is added

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Mind if you send me the crash report. It's most likely a Forge bug that can be fixed.

**Comment by p455w0rd** [comment]
it's not me, it's the linux users..and there's three of them, so i figure it's valid..deny the pull..i understand if u want the colors..i like to keep my stuff custom too

**Comment by toxicpsion** [comment]
logs at https://gist.github.com/toxicpsion/3224b08c7b4c7d587463 fyi

**Comment by 8wgremlin** [comment]
I have the same issue with Mac osX - can we get this merged?

**Comment by MrCrayfish** [comment]
Anyone able to confirm that this is still a problem on 1.8 version of Forge?

**Pull request closed without merging**
