### PR TITLE
1.12.2 Official Support

### PR DESCRIPTION
**Pull request by CDAGaming**
Status: Tested as Working & Building Successfully under Gradle 4.3

### CODE REVIEW

**Comment by MrCrayfish** [comment]
Will look into this soon! Just currently active on something else

**Comment by CDAGaming** [comment]
Ok, will Edit this PR once I'm home today.

**Comment by CDAGaming** [comment]
ToDo:
- ReUpdate Forge Changelog file and any other Forge MDK Files
- Update MCP Mappings to 20171024 and Forge to 2515

**Comment by CDAGaming** [comment]
@MrCrayfish Closing this PR for Now, am going to redo this with a different Goal at a later date.

**Pull request closed without merging**
